#!/bin/bash
#
# Script used to make available multi version
# at istex.github.io and widgets.istex.io
# il will generate folders this way: 
# - js/widgets.min.js
# - themes/default/widgets.min.css
# - latest/js/widgets.min.js
# - latest/themes/default/widgets.min.css
# - v1.2.1/js/widgets.min.js
# - v1.2.1/themes/default/widgets.min.css
# - v1.1.0/js/widgets.min.js
# - v1.1.0/themes/default/widgets.min.css
#

set -e

DIST_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )/../dist" && pwd )
cd $DIST_PATH

# check we are on the right repository
REPOSITORY_URL=$(git config --get remote.origin.url)
if [ $REPOSITORY_URL != "git@github.com:istex/istex.github.io.git" ]; then
  echo "Error: $(pwd) is not a clone of git@github.com:istex/istex.github.io.git"
  exit 1
fi
git pull --tags

# loop over versions
# and create a folder for each versions
for VERSION in $(git tag)
do
  echo "Creating $VERSION/"
  git archive --format=tar --prefix=$VERSION/ $VERSION | tar x
  # to avoid duplicating version folders recursivly
  rm -rf ./$VERSION/v*/
  rm -rf ./$VERSION/latest/
done